### PR TITLE
Update and segment documentation

### LINKED ISSUE #31: DaemonSet option in helm chart
Hi,

It will be nice if we can have an option to deploy the controller as a DaemonSet instead of Deployment to run on each node. See the controller.kind option in https://github.com/kubernetes/charts/tree/master/stable/nginx-ingress for an example. If DaemonSet then it implies loadbalancing true.

Regards,
Riaan

### LINKED ISSUE #38: Getting started example does not work
I followed the getting started tutorial in the readme and can't get the example working. 

The domain I had was the TLD associated with cloudflare account, and I used `httpbin.${mydomain.com}` as the `host` configuration in an ingress deployment file.

FWIW, when I used `cloudflared` directly to tunnel, I was able to see a dns record in my cloudflare account and it also worked. 
image
However, no such record got created when I tried to setup argo tunnel via the ingress controller. I tried using both the TLD as well as a subdomain for the domain passed in as `cloudflare-argo/domain` and neither approach worked. 

Here are the logs from argo tunnel pod when I try to apply the ingress `kubectl create -f argo.ingress.yaml`
```
I0813 02:30:46.467708       1 controller.go:185] Annotation kubernetes.io/ingress.class=argo-tunnel
I0813 02:30:46.467780       1 controller.go:610] creating tunnel for ingress httpbin, default/httpbin/httpbin
I0813 02:30:46.476709       1 round_trippers.go:436] GET https://10.96.0.1:443/api/v1/namespaces/default/secrets/cloudflared-cert 200 OK in 8 milliseconds
I0813 02:30:46.478739       1 controller.go:636] created tunnel for ingress httpbin,  default/httpbin/httpbin
I0813 02:30:46.478779       1 controller.go:699] Validation ok for running default/httpbin/httpbin with 1 endpoint(s)
I0813 02:30:46.478841       1 controller.go:723] Starting tunnel to url httpbin.default:80
I0813 02:30:46.485156       1 round_trippers.go:436] GET https://10.96.0.1:443/apis/extensions/v1beta1/namespaces/default/ingresses/httpbin 200 OK in 6 milliseconds
I0813 02:30:46.489599       1 round_trippers.go:436] PUT https://10.96.0.1:443/apis/extensions/v1beta1/namespaces/default/ingresses/httpbin/status 200 OK in 3 milliseconds
I0813 02:30:46.489817       1 controller.go:185] Annotation kubernetes.io/ingress.class=argo-tunnel
I0813 02:30:46.489849       1 controller.go:185] Annotation kubernetes.io/ingress.class=argo-tunnel
```

And here are the logs when I delete it `kubectl delete -f argo.ingress.yaml`

```
I0813 02:31:10.058995       1 controller.go:185] Annotation kubernetes.io/ingress.class=argo-tunnel
I0813 02:31:10.059101       1 controller.go:770] Removing tunnel default/httpbin/httpbin
I0813 02:31:10.059132       1 controller.go:502] Error processing delete:default/httpbin/httpbin: lookup cftunnel.com on 10.96.0.10:53: no such host
I0813 02:31:10.064582       1 controller.go:770] Removing tunnel default/httpbin/httpbin
I0813 02:31:10.064626       1 controller.go:502] Error processing delete:default/httpbin/httpbin: Tunnel not found for key default/httpbin/httpbin
I0813 02:31:10.075053       1 controller.go:770] Removing tunnel default/httpbin/httpbin
E0813 02:31:10.075128       1 controller.go:508] Dropping object "delete:default/httpbin/httpbin" out of the queue: Tunnel not found for key default/httpbin/httpbin
```

### LINKED ISSUE #45: Segment README.md into a series of guides
The goal is to split up the README.md into a series of guides that can be more focused and detailed, while leaving a simple landing page.

### PR DESCRIPTION
**Pull request by mattalberts**
The documentation is being split-off into targeted sections, keeping the
landing page focused on deploying and configuring the argo-tunnel
controller.

Other changes of note:
 - removes helm chart
 - removes roadmap
 - updated examples: echo
 - adds a series of guides

I understand that removing the help chart is an awkward way to resolve
the request for a daemonset variant. With the updates to the documents,
the installation has been simplified and is not driven through helm.

Once the project is connected to CI the contributing instructions will
be added.

fixes #45
fixes #38
fixes #31

### CODE REVIEW

**Comment by ntfrnzn** [comment]
Removing the helm chart is a mistake. A very large number of people find helm to be a useful and simplifying tool in deploying applications. I'm very surprised that it would be removed without discussion.

**Comment by mattalberts** [comment]
I'm looking for ways to reduce the surface area of what people need to know to quickly deploy use the ingress controller. There is already a lot to grasp in terms of tunnels.

The previous documentation drove users directly into using helm at the expense of both familiarity with helm and complicating secret deployment. After flattening the charts templates into a pre-build `argo-tunnel.yaml` and updating the docs, it was hard to understand the value add.  The only item left to configure is the namespace for the rbac (and possibly enabling rbac).

I generally find that helm provides a good mechanism to template an initial manifest using, `helm template`, and then tailor the manifest to my environment or to support configurations not expressed by the helm chart.

I definitely don't want helm to be perceived as a requirement. Given the simplicity of this controller deployment, is there truly value in the helm chart? Was it widely used by the community?

**Comment by ntfrnzn** [comment]
Regarding helm in general, it is both in wide use and also disputed as the best way to manage application deployments.  Even if it is not the easiest path for absolute beginners (or the preferred path for intermediates cough ksonnet), it's a reasonable standard that many people expect.

The chart is certainly in use by some people, so I think it is very fair to steer the intro-level documentation toward a simple manifest, but leave the chart in place for people who want to configure rbac or loadbalancing.

**Comment by mattalberts** [comment]
Perfect!  I came to a similar conclusion (independently :P ... I've spent the morning recovering the helm chart and adding a guide).

**Pull request merged**
